# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: 文章列表
  url: /archives/
  icon:
- page: 文章分类
  url: /categories/
  icon:
- page: 文章标签
  url: /tags/
  icon:
- page: 关于作者
  url: /about/
  icon:

## favicon
favicon: /img/site_logo.jpg

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: 
  url: 'javascript:'

## swipeBanner
swipeBanner:
# - img: https://image.chenhanpeng.com/static/images/web_static_image/head-img.jpg
#   url: /
- img: https://image.chenhanpeng.com/static/images/web_static_image/head-img-1.jpg
  url: /categories/前端

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  # - promo
  - social
  - category
  - archive
  - tagcloud
  - friends


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
# https://image.chenhanpeng.com/static/images/web_static_image/notification-gzh.png
notification: |-
            <p style="text-align:center;">
                <img src="https://image.chenhanpeng.com/fegeek_qrcode.png" style="width:360px;" />
            </p>

## 推广/广告位
promo:
      <p>
        <a href="/" target="_blank"> <img src="/" alt></a> <br />
      </p>

## 社交设置
social:
 - name: Github
   icon: github
   href: https://github.com/Hanpeng-Chen
 - name: 邮箱
   icon: envelope-o
   href: mailto:hanpengchen07@163.com
 - name: 掘金
   icon: magic
   href: https://juejin.cn/user/1063982988795911
 - name: 知乎
   icon: magic
   href: https://www.zhihu.com/people/hanpengchen
#  - name: 联系QQ
#    icon: qq
#    href: /
#  - name: 微信
#    icon: weixin
#    href: /
#  - name: QQ群
#    icon: users
#    href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: true
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  # - Hexo官网: https://hexo.io/zh-cn/

# 主题自定义个性化配置

## 网站宣传语
branding: Hanpeng Chen的个人博客

## 设置banner背景图片
banner:
    img: https://image.chenhanpeng.com/static/images/web_static_image/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 是否显示首页的缩略图
showImgs: false

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">代码视界</a>

## 文章打赏
reward:
  alipay: https://image.chenhanpeng.com/static/images/web_static_image/donate/alipay_qrcode.png
  wepay: https://image.chenhanpeng.com/static/images/web_static_image/donate/weixin_pay_qrcode.png
  tip: 赞赏是不耍流氓的鼓励

## 微信公众号
wechat:
  enable: true
  title: 欢迎关注微信公众号： 『前端极客技术』『代码视界』
  img: https://image.chenhanpeng.com/static/images/web_static_image/article-gzh-qrcode.png

## 主题评论

## Valine评论
valine:
   enable: false
   appId:
   appKey:
   placeholder:
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: 

## Gitalk评论
gitalk:
   enable: true
   clientID: fb80658382dee5240195
   clientSecret: 66663a08264192222ba993f20dd7c0a27c1e6fa5
   repo: blog-comments
   owner: Hanpeng-Chen
   admin: ['Hanpeng-Chen']
   perPage: 10
   distractionFreeMode: true
   language: zh-CN
   proxy: https://bold-forest-51f4.hanpengchen.workers.dev/?https://github.com/login/oauth/access_token

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id:


## 网站访客统计
visit_counter:
   site: false
   page: true

leancloud_visitors:
  enable: false
  app_id: #<app_id>
  app_key: #<app_key>
  # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
  # If you don't care about security in leancloud counter and just want to use it directly
  # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
  security: false
  betterPerformance: false

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics:

### 百度统计
baidu_analytics: 494af80fa01e8939bec179cfddf660d5

### 谷歌统计
google_analytics: UA-142577364-1

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification: rGeweWgWoh

### 百度自动推送
baidu_push: true

##备案信息
### ICP备案
icp:
  enable: true
  id: 闽ICP备19010134号-1
  url: //beian.miit.gov.cn/

### 公安备案
gongan_beian:
  enable: true
  icon: https://image.chenhanpeng.com/static/images/web_static_image/beian_icon.png
  id: 闽公网安备 35020302033449号
  url: http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=35020302033449

#网站主题配置
since: 2019
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.3
