categories: 分类
search: 搜索
tags: 标签
tagcloud: 标签云
tweets: Tweets
prev: 上一页
next: 下一页
comment: 评论
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: 近期文章
newer: Newer
older: Older
share: Share
rss_feed: RSS
rss: RSS
category: Category
tag: Tag
social: 社交
friend_links: 友链
read_more: 阅读全文
home: Home
archives: 归档
about: 关于
search_local: 站内搜索
search_google: googleSearch
search_placeholder: Search What？
author: Author
date: Published Date
update: Updated Date
post_categories: Categories
post_tags: Tags
post_licence: License
notification: 网站公告
toc: Table of Contents
visit_counter_uv: Visitors
visit_counter_pv: Total
